added updated workflow

diff --git a/.github/workflows/pylint_intgrate.yml b/.github/workflows/pylint_intgrate.yml
--- a/.github/workflows/pylint_intgrate.yml
+++ b/.github/workflows/pylint_intgrate.yml
@@ -12,12 +12,12 @@ jobs:
       run: pip install pylint pytest pytest-cov
     - name: Run PyLint and generate report
       run: |
-        pylint --output-format=.coverage --fail-under=9 ./**/*.py > pylint_report.coverage || echo "FAILED"
+        pylint --output-format=text --fail-under=9 ./**/*.py > pylint_report.txt || echo "FAILED"
 
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v1
       with:
-          token: ${{ secrets.YOUR_SECRET_TOKEN }}
+          token: ${{ secrets.YOUR_SECRET_TOKEN }} -f pylint_report.txt
 
     # - name: Upload coverage reports to Codecov
     #   run: |
