added updated workflow

diff --git a/.github/workflows/pylint_intgrate.yml b/.github/workflows/pylint_intgrate.yml
--- a/.github/workflows/pylint_intgrate.yml
+++ b/.github/workflows/pylint_intgrate.yml
@@ -10,6 +10,10 @@ jobs:
     - uses: actions/checkout@v1
     - name: Install requirements
       run:  pip install pylint pytest pytest-cov
+    - name: Run PyLint and generate report
+      run: |
+        pylint --output-format=text --fail-under=9 ./**/*.py > pylint_report.txt || echo "FAILED"
+
     - name: Run tests and collect coverage
       run: pytest --cov .
     - name: Upload coverage reports to Codecov
@@ -18,4 +22,4 @@ jobs:
         # Options are `alpine`, `linux`, `macos`, `windows`
         curl -Os https://uploader.codecov.io/latest/linux/codecov
         chmod +x codecov
-        ./codecov -t ${{ secrets.CODECOV_TOKEN }}
+        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f pylint_report.txt
