added updated workflow

diff --git a/.github/workflows/pylint_intgrate.yml b/.github/workflows/pylint_intgrate.yml
--- a/.github/workflows/pylint_intgrate.yml
+++ b/.github/workflows/pylint_intgrate.yml
@@ -12,7 +12,7 @@ jobs:
       run: pip install pylint pytest pytest-cov
     - name: Run PyLint and generate report
       run: |
-        pylint --output-format=json --fail-under=9 ./**/*.py > pylint_report.json || echo "FAILED"
+        pylint --output-format=html --fail-under=9 ./**/*.py > pylint_report.json || echo "FAILED"
     - name: Upload coverage reports to Codecov
       run: |
         # Replace `linux` below with the appropriate OS
