added updated workflow

diff --git a/.github/workflows/pylint_intgrate.yml b/.github/workflows/pylint_intgrate.yml
--- a/.github/workflows/pylint_intgrate.yml
+++ b/.github/workflows/pylint_intgrate.yml
@@ -9,15 +9,14 @@ jobs:
     steps:
     - uses: actions/checkout@v1
     - name: Install requirements
-      run:  pip install pylint pytest pytest-cov
+      run: pip install pylint pytest pytest-cov
     - name: Run PyLint and generate report
       run: |
-        pylint --output-format=parseable --fail-under=9 ./**/*.py > pylint_report.txt || echo "FAILED"
-
+        pylint --output-format=json --fail-under=9 ./**/*.py > pylint_report.json || echo "FAILED"
     - name: Upload coverage reports to Codecov
       run: |
         # Replace `linux` below with the appropriate OS
         # Options are `alpine`, `linux`, `macos`, `windows`
         curl -Os https://uploader.codecov.io/latest/linux/codecov
         chmod +x codecov
-        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f pylint_report.txt
+        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f pylint_report.json
