added updated workflow

diff --git a/.github/workflows/pylint_intgrate.yml b/.github/workflows/pylint_intgrate.yml
--- a/.github/workflows/pylint_intgrate.yml
+++ b/.github/workflows/pylint_intgrate.yml
@@ -12,7 +12,7 @@ jobs:
       run:  pip install pylint pytest pytest-cov
     - name: Run PyLint and generate report
       run: |
-        pylint --output-format=text --fail-under=9 ./**/*.py > pylint_report.txt || echo "FAILED"
+        pylint --output-format=parseable --fail-under=9 ./**/*.py > pylint_report.txt || echo "FAILED"
 
     - name: Upload coverage reports to Codecov
       run: |
